version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: trucklink
      POSTGRES_DB: trucklink
    ports: ['5432:5432']
    volumes: ['./data/postgres:/var/lib/postgresql/data']

  redis:
    image: redis:7
    ports: ['6379:6379']

  backend:
    build: ./backend
    env_file: ./.env
    depends_on: ['db','redis']
    ports: ['4000:4000']

  frontend:
    build: ./frontend
    ports: ['3000:3000']
